# Generated by Django 5.0.6 on 2024-06-24 01:39

import django.contrib.auth.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gym", "0002_alter_billingplan_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.contrib.auth.models.User,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name=django.contrib.auth.models.User,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=255, verbose_name=django.contrib.auth.models.User
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=255, verbose_name=django.contrib.auth.models.User
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, verbose_name=django.contrib.auth.models.User
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name=django.contrib.auth.models.User
                    ),
                ),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym.activitymodality",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym.activityplan",
                    ),
                ),
            ],
        ),
    ]
