# Generated by Django 5.0.6 on 2024-06-24 03:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="clients",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="clients",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="clients",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="clients",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
