# Generated by Django 5.0.6 on 2024-06-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrator",
            "0002_alter_clients_date_joined_alter_clients_email_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Clients",
        ),
    ]
