# Generated by Django 5.0.6 on 2024-06-25 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administrator", "0003_delete_clients"),
        ("gym", "0003_billingplan_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("certification", models.CharField(max_length=250)),
                ("identification", models.IntegerField(max_length=20)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym.activityplan",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym.billingplan",
                    ),
                ),
            ],
        ),
    ]
