# Generated by Django 5.0.6 on 2024-06-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="identification",
            field=models.IntegerField(),
        ),
    ]
