# Generated by Django 5.0.6 on 2024-07-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_employee_identification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
