# Generated by Django 5.0.6 on 2024-07-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0006_employees_delete_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "verbose_name": "class",
                "verbose_name_plural": "classes",
                "ordering": ["name"],
            },
        ),
    ]
