# Generated by Django 5.0.6 on 2024-06-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
