# Generated by Django 5.0.6 on 2024-06-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_billingplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
